name: Dependency Submission

on:
  push:
  workflow_dispatch:

jobs:
  maintenance_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.1
      - uses: actions/setup-java@v4.4.0
        name: Setup Java
        with:
          distribution: temurin
          java-version: 11
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3.5.0
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
        env:
          # Include only relevant configurations
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '(implementation|api|compileClasspath|runtimeClasspath)'
